### ISSUE TITLE
Name method not  matching what it does

### ISSUE THREAD

**Issue by alexandernst** [shkliciouz/Image-Editor-API-Like#16]
The method `kindOfSource` doesn't do what the name says (which is a sign of bad code design). I'd expect from a method called `kindOfSource` (which, btw, would be better called `typeOfSource`) to return the type of the source I have passed, rather than a file handle (that would be probably a good job for a method called `openSource`).

**Comment by marioshki** [comment]
https://github.com/mariomvp/Image-Editor-API-Like/commit/187281ae61d95d854f0cd7a2a34892316f11c576
