### ISSUE TITLE
Support cropping

### ISSUE THREAD

**Issue by alexandernst** [shkliciouz/Image-Editor-API-Like#4]
Cropping is an important function. Add support for it.

**Comment by marioshki** [comment]
https://github.com/shkrz/Image-Editor-API-Like/commit/324d18e7c958c76253945d806c000fe37d54c0bc

**Comment by alexandernst** [comment]
This doesn't quite cut it.Make it more usable with "good" default values and cropping strategies.

If no X/Y coords given, make it start from 0,0.
If no w/h given, make is crop respecting ratio.

**Comment by marioshki** [comment]
Cut the image from 0,0 has no sense :confounded:  it is supposed to cut a part you specified in the args, noone (probably) wants cut from 0,0 position, it has more sense if by default cuts from the center of the image or something alike...

And what do you mean with "respecting ratio"? If you dont give a "size to cut" , it means you dont wanna cut a part of, i cant see it :confounded:

**Comment by alexandernst** [comment]
Those were just examples, you're free to make the default values what you think it would be used most. Just keep in mind that your library could be used to resize/crop/xyz images without knowing their size previously, which means that possible use-cases could be:
- Create a 32x32px image of `<current image>`, being the `<center of the image> - (32/2)` the starting point. (aka, cut a 32x32 image from the current image, preserving the center).
- Crop this image by 15px from the left/right and 20px from the top/bottom (without giving specific coordinates)
- etc...

Use your imagination, I'm sure you'll find a lot of use-cases. Maybe a good source of inspiration could be to actually build a parallel project (an example-like project) that uses this library.
